feat: plan remove swa

diff --git a/.github/workflows/terraform-plan.yml b/.github/workflows/terraform-plan.yml
--- a/.github/workflows/terraform-plan.yml
+++ b/.github/workflows/terraform-plan.yml
@@ -72,35 +72,6 @@ on:
         type: string
         default: ""
 
-      remote_state_swa_assume_role_role_arn:
-        required: false
-        type: string
-      remote_state_swa_assume_role_role_session_name:
-        required: false
-        type: string
-        default: "GitHubActions"
-      remote_state_swa_bucket:
-        required: false
-        type: string
-      remote_state_swa_dynamodb_table:
-        required: false
-        type: string
-      remote_state_swa_encrypt:
-        required: false
-        type: boolean
-        default: true
-      remote_state_swa_kms_key_id:
-        required: false
-        type: string
-      remote_state_swa_plan_folder:
-        required: false
-        type: string
-      remote_state_swa_region:
-        required: false
-        type: string
-      remote_state_swa_state_folder:
-        required: false
-        type: string
       remote_state_azure_plan_container_name:
         required: false
         type: string
@@ -164,15 +135,6 @@ jobs:
       shared_tfvar_values: ${{ inputs.shared_tfvar_values }}
       tfvars: ${{ inputs.tfvars }}
 
-      remote_state_swa_assume_role_role_arn: ${{ inputs.remote_state_swa_assume_role_role_arn }}
-      remote_state_swa_assume_role_role_session_name: ${{ inputs.remote_state_swa_assume_role_role_session_name }}
-      remote_state_swa_bucket: ${{ inputs.remote_state_swa_bucket }}
-      remote_state_swa_dynamodb_table: ${{ inputs.remote_state_swa_dynamodb_table }}
-      remote_state_swa_encrypt: ${{ inputs.remote_state_swa_encrypt }}
-      remote_state_swa_kms_key_id: ${{ inputs.remote_state_swa_kms_key_id }}
-      remote_state_swa_plan_folder: ${{ inputs.remote_state_swa_plan_folder }}
-      remote_state_swa_region: ${{ inputs.remote_state_swa_region }}
-      remote_state_swa_state_folder: ${{ inputs.remote_state_swa_state_folder }}
       remote_state_azure_plan_container_name: ${{ inputs.remote_state_azure_plan_container_name }}
       remote_state_azure_resource_group_name: ${{ inputs.remote_state_azure_resource_group_name }}
       remote_state_azure_state_container_name: ${{ inputs.remote_state_azure_state_container_name }}
@@ -187,8 +149,8 @@ jobs:
 
       - name: Validate `cloud_provider` input
         run: |
-          if [[ "${cloud_provider}" != "swa" ]] && [[ "${cloud_provider}" != "azure" ]]; then
-            echo 'The specified `cloud_provider` value is invalid: `${{ inputs.cloud_provider }}`. Acceptable values are `swa` and `azure`.'
+          if [[ "${cloud_provider}" != "azure" ]]; then
+            echo 'The specified `cloud_provider` value is invalid: `${{ inputs.cloud_provider }}`. Acceptable values is `azure`.'
             exit 1
           fi
 
@@ -247,8 +209,9 @@ jobs:
       - name: Set plan name
         id: set_plan_name
         run: |
-          if [[ "${cloud_provider}" == 'swa' ]]; then # other provider
-            plan_name="${remote_state_swa_state_folder}-${branch_ref}-${job_name}-${{ github.run_id }}-${{ github.run_attempt }}.tfplan"
+          if [[ "${cloud_provider}" != 'azure' ]]; then # other provider
+            echo "NOT supported"
+            exit 1
           else # Azure
             plan_name="${remote_state_azure_state_container_name}-${branch_ref}-${job_name}-${{ github.run_id }}-${{ github.run_attempt }}.tfplan"
           fi
@@ -258,8 +221,9 @@ jobs:
       - name: Set backend config key
         run: |
           if [ -z "${remote_state_key}" ]; then
-            if [[ "${cloud_provider}" == 'swa' ]]; then # other provider
-              remote_state_key="${remote_state_swa_state_folder}/${remote_state_swa_state_folder}-${branch_ref}-${job_name}.tfstate"
+            if [[ "${cloud_provider}" != 'azure' ]]; then # other provider
+              echo "NOT supported"
+              exit 1
             else # Azure
               remote_state_key="${remote_state_azure_state_container_name}-${branch_ref}-${job_name}.tfstate"
             fi
@@ -322,7 +286,7 @@ jobs:
           GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
         run: |
           echo "backend-config=resource_group_name=[${{ env.remote_state_azure_resource_group_name }}] "
-          if [[ "${cloud_provider}" == 'swa' ]]; then # other provider
+          if [[ "${cloud_provider}" != 'azure' ]]; then # other provider
             echo "Not supported"
           elif [[ "${cloud_provider}" == 'azure' && '${{ env.ARM_CLIENT_SECRET }}' != '' ]]; then # Azure w/ client secret
             terraform init \
@@ -367,20 +331,8 @@ jobs:
       - name: Store plan
         if: ${{ !inputs.run_plan_only }}
         run: |
-          if [[ "${cloud_provider}" == 'swa' ]]; then # other provider
-            echo 'Uploading plan file to S3 Bucket as "${{ env.plan_name }}"...'
-
-            upload_options=''
-            if [[ "${remote_state_swa_kms_key_id}" != '' ]]; then
-              upload_options='--sse swa:kms --sse-kms-key-id ${{ env.remote_state_swa_kms_key_id }}'
-            elif [[ "${remote_state_swa_encrypt}" == 'true' ]]; then
-              upload_options='--sse AES256'
-            fi
-            echo "upload_options = ${upload_options}"
-
-            swa s3 cp "${{ env.plan_name }}" "s3://${{ env.remote_state_swa_bucket }}/${{ env.remote_state_swa_plan_folder }}/${{ env.plan_name }}" ${upload_options}
-
-            echo 'Uploading plan file to S3 Bucket as "${{ env.plan_name }}"... completed.'
+          if [[ "${cloud_provider}" != 'azure' ]]; then # other provider
+            echo "NOT supported"
           else # Azure
             echo 'Uploading plan file to "${{ env.remote_state_azure_plan_container_name }}" Storage Container as "${{ env.plan_name }}"...'
 
